# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e3e2e4"

# Title color for boxes
theme[title]="#b2c8e9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#bfc7d6"

# Background color of selected item in processes box
theme[selected_bg]="#b2c8e9"

# Foreground color of selected item in processes box
theme[selected_fg]="#1b314c"

# Color of inactive/disabled text
theme[inactive_fg]="#c4c6ce"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#e3c28a"

# Cpu box outline color
theme[cpu_box]="#8e9198"

# Memory/disks box outline color
theme[mem_box]="#8e9198"

# Net up/down box outline color
theme[net_box]="#8e9198"

# Processes box outline color
theme[proc_box]="#8e9198"

# Box divider line and small boxes line color
theme[div_line]="#43474d"

# Temperature graph colors
theme[temp_start]="#bfc7d6"
theme[temp_mid]="#b2c8e9"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#bfc7d6"
theme[cpu_mid]="#b2c8e9"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#bfc7d6"
theme[free_mid]=""
theme[free_end]="#3f4753"

# Mem/Disk cached meter
theme[cached_start]="#e3c28a"
theme[cached_mid]=""
theme[cached_end]="#493409"

# Mem/Disk available meter
theme[available_start]="#b2c8e9"
theme[available_mid]=""
theme[available_end]="#233954"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#bfc7d6"
theme[download_mid]="#b2c8e9"
theme[download_end]="#e3c28a"

# Upload graph colors
theme[upload_start]="#bfc7d6"
theme[upload_mid]="#b2c8e9"
theme[upload_end]="#e3c28a"
