cursor #ffd54f
cursor_text_color #14100a

foreground            #ffe0a3
background            #14100a
selection_foreground  #14100a
selection_background  #ff8f00
url_color             #ffb000

color0   #1e1810
color1   #ff5722
color2   #ffd54f
color3   #ffb000
color4   #ff8f00
color5   #c77700
color6   #ffe082
color7   #ffe0a3
color8   #4a3a20
color9   #ff8a65
color10  #ffecb3
color11  #ffca28
color12  #ffcc80
color13  #ffd180
color14  #fff8e1
color15  #fffde7

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #14100a

tab_bar_background              #14100a

active_tab_foreground           #14100a
active_tab_background           #ffb000
active_tab_font_style           bold

inactive_tab_foreground         #ffe0a3
inactive_tab_background         #14100a
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
