cursor #5eead4
cursor_text_color #0c1613

foreground            #d5f4ec
background            #0c1613
selection_foreground  #0c1613
selection_background  #14b8a6
url_color             #2dd4a8

color0   #12211c
color1   #f87171
color2   #4ade80
color3   #facc15
color4   #2dd4a8
color5   #0d9488
color6   #5eead4
color7   #d5f4ec
color8   #33463f
color9   #fca5a5
color10  #86efac
color11  #fde047
color12  #7ef0d4
color13  #99f6e4
color14  #ccfbf1
color15  #f0fdf9

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #0c1613

tab_bar_background              #0c1613

active_tab_foreground           #0c1613
active_tab_background           #2dd4a8
active_tab_font_style           bold

inactive_tab_foreground         #d5f4ec
inactive_tab_background         #0c1613
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
