cursor #83a598
cursor_text_color #282828

foreground            #ebdbb2
background            #282828
selection_foreground  #282828
selection_background  #fabd2f
url_color             #fe8019

color0   #282828
color1   #cc241d
color2   #98971a
color3   #d79921
color4   #458588
color5   #b16286
color6   #689d6a
color7   #a89984
color8   #928374
color9   #fb4934
color10  #b8bb26
color11  #fabd2f
color12  #83a598
color13  #d3869b
color14  #8ec07c
color15  #ebdbb2

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #282828

tab_bar_background              #282828

active_tab_foreground           #282828
active_tab_background           #fe8019
active_tab_font_style           bold

inactive_tab_foreground         #ebdbb2
inactive_tab_background         #282828
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
