cursor #ccd5ae
cursor_text_color #1c1512

foreground            #e6ccb2
background            #1c1512
selection_foreground  #1c1512
selection_background  #e6ccb2
url_color             #d4a373

color0   #261c17
color1   #bc4749
color2   #a3b18a
color3   #d4a373
color4   #8d6e63
color5   #b08968
color6   #ccd5ae
color7   #ede0d4
color8   #5b4636
color9   #e5989b
color10  #b7c9a8
color11  #e6ccb2
color12  #ddba9b
color13  #cfae8f
color14  #ffe5d9
color15  #f5ebe0

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #1c1512

tab_bar_background              #1c1512

active_tab_foreground           #1c1512
active_tab_background           #d4a373
active_tab_font_style           bold

inactive_tab_foreground         #e6ccb2
inactive_tab_background         #1c1512
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
