cursor #8fbcbb
cursor_text_color #2e3440

foreground            #d8dee9
background            #2e3440
selection_foreground  #2e3440
selection_background  #81a1c1
url_color             #88c0d0

color0   #3b4252
color1   #bf616a
color2   #a3be8c
color3   #ebcb8b
color4   #81a1c1
color5   #b48ead
color6   #88c0d0
color7   #e5e9f0
color8   #4c566a
color9   #d08770
color10  #a3be8c
color11  #ebcb8b
color12  #81a1c1
color13  #b48ead
color14  #8fbcbb
color15  #eceff4

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #2e3440

tab_bar_background              #2e3440

active_tab_foreground           #2e3440
active_tab_background           #88c0d0
active_tab_font_style           bold

inactive_tab_foreground         #d8dee9
inactive_tab_background         #2e3440
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
