cursor #bde0fe
cursor_text_color #1c1218

foreground            #ffe5ec
background            #1c1218
selection_foreground  #1c1218
selection_background  #ffc2d4
url_color             #ff9ebb

color0   #271822
color1   #ff5d8f
color2   #bde0fe
color3   #ffc2d4
color4   #ff9ebb
color5   #c9184a
color6   #a2d2ff
color7   #ffe5ec
color8   #5c3648
color9   #ff8fab
color10  #cdb4db
color11  #ffd6e0
color12  #a2d2ff
color13  #ffc8dd
color14  #e2ece9
color15  #fff0f3

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #1c1218

tab_bar_background              #1c1218

active_tab_foreground           #1c1218
active_tab_background           #ff9ebb
active_tab_font_style           bold

inactive_tab_foreground         #ffe5ec
inactive_tab_background         #1c1218
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
