cursor #73daca
cursor_text_color #16161e

foreground            #cbccd1
background            #16161e
selection_foreground  #16161e
selection_background  #bb9af7
url_color             #7aa2f7

color0   #1a1b26
color1   #ff7198
color2   #7af78c
color3   #fff871
color4   #5c89ea
color5   #082a72
color6   #7aa2f7
color7   #eff4ff
color8   #494c52
color9   #ff9eb9
color10  #a4ffb2
color11  #fffaa4
color12  #91b4ff
color13  #a4c1ff
color14  #c4d7ff
color15  #f8faff

tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left
tab_bar_min_tabs        2
tab_bar_margin_width    0.0
tab_bar_margin_height   2.5 1.5
tab_bar_margin_color    #16161e

tab_bar_background              #16161e

active_tab_foreground           #16161e
active_tab_background           #7aa2f7
active_tab_font_style           bold

inactive_tab_foreground         #cbccd1
inactive_tab_background         #16161e
inactive_tab_font_style         normal

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
