cursor #e3e2e4
cursor_text_color #c4c6ce

foreground            #e3e2e4
background            #121315
selection_foreground  #29313c
selection_background  #bfc7d6
url_color             #b2c8e9

color0   #121315
color1   #ff729b
color2   #74e985
color3   #fff872
color4   #9eb7dd
color5   #3d4f6b
color6   #b2c8e9
color7   #e5ebf4
color8   #3f4247
color9   #ff9fba
color10  #a5ffb2
color11  #fffaa5
color12  #cbe0ff
color13  #d4e5ff
color14  #e3eeff
color15  #f8fbff
